---
title: "NonStandardNSE"
author: "Rafał Muszyński"
date: "11/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rlang)
```

```{r}

test_nse <- function(nse_constructor){
  test_min <- nse_constructor(min)
  print(test_min(list(a=c(4,5,6), b=c(512,23,1,1)), a))
  
  test_mean <- nse_constructor(mean)
  print(test_mean(list(a=c(4,5,6), b=c(512,23,1,1)), b))
  
  test_print <- nse_constructor(print)
  test_print(list(x = 'hmmmmm'), x, quote=TRUE)
  
  data(iris)
  print(lm(formula = Sepal.Length~Sepal.Width, iris))
  test_lm <- nse_constructor(lm)
  print(test_lm(iris, formula = Sepal.Length~Sepal.Width))
  print(lm(formula = Sepal.Length~Sepal.Width - 1, iris))
  print(test_lm(iris, formula = Sepal.Length~Sepal.Width - 1))
  
  test_unlist <- nse_constructor(unlist)
  print(test_unlist(list( x=list(x = 1, y = 2, z = 3, w = c('aa', 'bb'))), x, use.names=FALSE))
  print(test_unlist(list( x=list(x = 1, y = 2, z = 3, w = c('aa', 'bb'))), x, use.names=TRUE))
  
  test_func <- function(func){
    print(func)
  }
  
  nse_constructor(test_func)(list(func=c(1,2,3)), func)

  something <- c(5,2,3,6)
  nse_constructor(min)(list(a=c(5,8,8,8,3,4)), something)
  
}

```


#my NSE VOL1



```{r}
# simple approach

simple_nse <- function(func){
  function(input_list, ...){
    eval(
      substitute(func(...)), 
      input_list
    )
  }
}

test_nse(simple_nse)

```


#NSE vol 2

```{r}
# improved version of simple nse, allows arguments from parent scope
advanced_nse <- function(func){
  function(input_list, ...){
    do.call(func, 
      eval(
        substitute(list(...)), 
        input_list,
        parent.frame()
      )
    )
  }
}



test_nse(advanced_nse)
something = c(5,4,2,6,1)
simple_nse(min)(list(a=c(5,8,8,8,3,4)), something)
advanced_nse(min)(list(a=c(5,8,8,8,3,4)), something)

```

```{r}
library(tidyr)

rlang_nse <- function(func){
  function(input_list, ...){
    args <- lapply(exprs(...), function(expr){
      rlang::eval_tidy(expr, input_list)
    })
    
    do.call(
      func, 
      args
    )
  }
}

rlang_nse(min)(list(a=c(4,2,3)), a)


test_nse(rlang_nse)

```


```{r}
# define benchmark function
library(microbenchmark)
library(ggplot2)

benchmark_function <- function(nse_constructor, nse_constructor_name){
  min_nse <- nse_constructor(min)
  mean_nse <- nse_constructor(mean)
  data(iris)
  lm_nse <- nse_constructor(lm)
  unlist_nse <- nse_constructor(unlist)

  results <- microbenchmark(
    min_nse(list(a=c(4,5,6), b=c(512,23,1,1)), a),
    mean_nse(list(a=c(4,5,6), b=c(512,23,1,1)), b),
    lm_nse(iris, formula = Sepal.Length~Sepal.Width - 1),
    unlist_nse(list( x=list(x = 1, y = 2, z = 3, w = c('aa', 'bb'))), x, use.names=FALSE),
    unlist_nse(list( x=list(x = 1, y = 2, z = 3, w = c('aa', 'bb'))), x, use.names=TRUE),
    times=1000L
  )
  results <- summary(results)
  test_names <- c('min', 'mean', 'lm', 'unlist_names', 'unlist_no_names')
  cbind(results, data.frame(method=nse_constructor_name), data.frame(tests = test_names))
}

```


```{r}

library(ggplot2)

results <- rbind(
  benchmark_function(simple_nse, 'simple nse'),
  benchmark_function(advanced_nse, 'advanced_nse'),
  benchmark_function(advanced_nse, 'rlang_nse')
)

ggplot(results, aes(x=tests, y=mean, fill=method)) +
  geom_bar(stat='identity', position='dodge') +
  scale_y_log10()

```

