---
title: "BGranat wyj "
author: "Bartlomiej Granat"
date: "12/19/2019"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Kodzik

```{r results='hide',message=FALSE,warning=FALSE}
library(kernlab)
library(mlr)

data(ticdata)
ticdata$CARAVAN
# 1 noinsurance 2 insurance
ticdata$CARAVAN <- as.factor(as.numeric(ticdata$CARAVAN))
summary(ticdata)


lrn_ranger <- makeLearner("classif.ranger", predict.type = "prob", id = "ranger")
lrn_fl <- makeLearner("classif.featureless", predict.type = "prob", id = "fl")
lrn_ctree <- makeLearner("classif.ctree", predict.type = "prob", id = "ctree")

lrns = list(lrn_ctree,lrn_ranger)

ticdata_task = makeClassifTask(id = "ticdata_task", data = ticdata, 
                                target = "CARAVAN")

rdesc = makeResampleDesc("CV", iters = 3L)
bmr = benchmark(lrns, ticdata_task, rdesc, measures = auc)
```

# Wyniki

```{r}
getBMRAggrPerformances(bmr)
plotBMRSummary(bmr)
```

# Zagniezdzona kroswalidacja dla lepszego learnera

```{r eval = FALSE}
outer <- makeResampleDesc(method = "CV", iters = 3)
inner <- makeResampleDesc(method = "CV", iters = 5)

ranger_wrapper <- makeTuneWrapper(learner = makeLearner("classif.ranger", predict.type = "prob"), 
                                  resampling = inner, 
                                  par.set = makeParamSet(makeIntegerParam(id = "num.trees", lower = 50, upper = 100)),
                                  control = makeTuneControlGrid(resolution = 5))

rsp <- resample(learner = ranger_wrapper, task = ticdata_task, resampling = outer, measures = auc, 
                extract = getTuneResult)

```