---
title: "Untitled"
author: "Andrzej Nowikowski"
date: "December 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

```{r}
library(kernlab)
data(spam)
train_data <- spam
head(train_data)
```

## Including Plots

You can also embed plots, for example:

```{r, warning=FALSE}

library(mlr)
library(ranger)


rf <- makeLearner("classif.ranger", id="1", predict.type="prob")

task <- makeClassifTask(id="titanic", data=train_data, target= "type")
fv = generateFilterValuesData(task, method = "FSelectorRcpp_information.gain")
task = filterFeatures(task, fval = fv, perc = 0.25)

outer <- makeResampleDesc(method = "CV", iters = 3)
inner <- makeResampleDesc(method = "CV", iters = 5)

ranger_wrapper <- makeTuneWrapper(learner=makeLearner('classif.ranger',predict.type = "prob"), 
                resampling = inner,
                par.set= makeParamSet(makeIntegerParam(id="num.trees",lower = 50, upper=1000)),
                control= makeTuneControlGrid(resolution=5)
                )

rsp <- resample(learner = ranger_wrapper, task = task, resampling = outer, measures=auc, 
         extract= getTuneResult)

rsp

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
