---
title: "Klonecki_wyjsciowka4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mlr)
library(drake)
library(dplyr)

wyjsciowka <- drake_plan(
  dat = read.csv("https://raw.githubusercontent.com/mini-pw/2020Z-ProgramowanieWR/master/Wyjsciowki/W2/gr1/SawickiJan/ShinyIris/iris.csv"),
  preprocessing = mutate(dat, variety = ifelse(variety == 'Setosa', 'Setosa', 'Other')),
  task = makeClassifTask(id = "drake_test", data = preprocessing, target = "variety"),
  bench = benchmark(learners = list(makeLearner("classif.randomForest"),
                                    makeLearner("classif.ksvm"),
                                    makeLearner("classif.nnet")
                                    ),
                    tasks = task),
  plot = plotBMRBoxplots(bench),
  save_bench = write.csv(dat, "model_input_data.csv")
)

make(wyjsciowka)
```
```{r}
readd(plot)
```
```{r}
vis_drake_graph(drake_config(wyjsciowka))

```

