---
title: "Tomasz Klonecki PD1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE)

```
## 1. Wstęp
Dane pochodzą z Kaggle i dotyczą ofert mieszkaniowych w Nowym Jorku z serwisu Airbnb.
W zadaniu porównam szybkość generowania wykresów w 3 poniższych bibliotekach:

* *graphics*
* *ggplot2*
* *lattice*

Każdy z wykresów w danym podpunkcie będę się starał wygenerować w miarę podobnie do pozostałych, tak żeby porównywać czas generowania jak najbardziej zbliżonych efektów.

```{R, echo = FALSE, include = FALSE}
library(graphics)
library(ggplot2)
library(lattice)

library(dplyr)
library(microbenchmark)

ny_data <- read.csv('AB_NYC_2019.csv')

```
## 2. Wykresy
### 2.1 Bar plot
Na początku porównam najbardziej podstawowy rodzaj wykresu jakim jest wykres słupkowy.
```{R, fig.align='center'}
nbhood_agg <- ny_data %>% 
  group_by(neighbourhood_group) %>% 
  summarize(avg_price = mean(price)) %>% 
  arrange(desc(avg_price))

# graphics
  graphics::barplot(avg_price ~ sort(neighbourhood_group), 
                  data = nbhood_agg,
                  col = heat.colors(12),
                  ylim = c(0,200),
                  main = 'Średnia cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Średnia cena [$]')

# ggplot2
ggplot(data = nbhood_agg, aes(x=sort(neighbourhood_group), y=avg_price)) + 
  geom_bar(stat = 'identity', aes(fill = avg_price)) +
  theme_minimal() +  
  scale_fill_gradient(low = "orange", high = "red")+
  theme(legend.title = element_blank(),
        legend.position = "none") +
  ggtitle('Średnia cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku') +
  labs(y='Średnia cena [$]', x = 'Dzielnica')

# lattice
lattice::barchart(avg_price ~ sort(neighbourhood_group), 
                  data = nbhood_agg,
                  col = heat.colors(12),
                  ylim = c(0,200),
                  main = 'Średnia cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Średnia cena [$]')
```

```{R, fig.show = 'hide',echo = FALSE, include = FALSE}
bar_results <- microbenchmark(
  
  graphics = graphics::barplot(avg_price ~ sort(neighbourhood_group), 
                  data = nbhood_agg,
                  col = heat.colors(12),
                  ylim = c(0,200),
                  main = 'Średnia cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Średnia cena [$]')
,

# ggplot2
ggplot2 = ggplot(data = nbhood_agg, aes(x=sort(neighbourhood_group), y=avg_price)) + 
  geom_bar(stat = 'identity', aes(fill = avg_price)) +
  theme_minimal() +  
  scale_fill_gradient(low = "orange", high = "red")+
  theme(legend.title = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  ggtitle('Średnia cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku') +
  labs(y='Średnia cena [$]', x = 'Dzielnica')
,

# lattice
lattice = lattice::barchart(avg_price ~ sort(neighbourhood_group), 
                  data = nbhood_agg,
                  col = heat.colors(12),
                  ylim = c(0,200),
                  main = 'Średnia cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Średnia cena [$]')
)
```

Wykres wiolinowy poniżej prezentuje 100 różnych czasów generowania dla każdej biblioteki. Możemy zauważyć, że najszybszą biblioteką okazuje się *lattice*.

```{R, fig.height=4, fig.width=4, echo = FALSE,message = FALSE, warnings = FALSE, fig.align='center'}
autoplot(bar_results) +
  ggtitle('Czas generowania wykresów \n Bar Plot') +
  theme(plot.title = element_text(hjust = 0.5))
```

### 2.2 Box plot
Jednak żeby lepiej zrozumieć dane dotyczące cen za nocleg, warto zobaczyć je na wykresie pudełkowym
```{R, fig.align='center'}
# graphics
  graphics::boxplot(price ~ sort(neighbourhood_group), 
                  data = ny_data,
                  col = heat.colors(12),
                  main = 'Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Cena [$]')

# ggplot2
ggplot(data = ny_data, aes(x=sort(neighbourhood_group), y=price)) + 
  geom_boxplot() +
  theme_minimal() +  
  scale_fill_gradient(low = "orange", high = "red")+
  theme(legend.title = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  ggtitle('Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku') +
  labs(y='Cena [$]', x = 'Dzielnica')

# lattice
lattice::bwplot(price ~ sort(neighbourhood_group), 
                  data = ny_data,
                  main = 'Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Cena [$]')
```

```{R, fig.show = 'hide',echo = FALSE, include = FALSE}
box_results <- microbenchmark(
  
  graphics = graphics::boxplot(price ~ sort(neighbourhood_group), 
                  data = ny_data,
                  main = 'Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Cena [$]')
,

# ggplot2
ggplot2 = ggplot(data = ny_data, aes(x=sort(neighbourhood_group), y=price)) + 
  geom_boxplot() +
  theme_minimal() +  
  theme(legend.title = element_blank(),
        legend.position = "none") +
  ggtitle('Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku') +
  labs(y='Cena [$]', x = 'Dzielnica')
,

# lattice
lattice = lattice::bwplot(price ~ sort(neighbourhood_group), 
                  data = ny_data,
                  main = 'Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Cena [$]')
)
```

Wykres wiolinowy poniżej prezentuje 100 różnych czasów generowania dla każdej biblioteki. Tym razem okazuje się, że najszybszy w generowaniu wykresów pudełkowych jest ggplot. Dla tego typu wykresu zostawiłem domyślne parametrym, więc bardzo możliwe że w ogóle ggplot może być najszybszy. Sprawdzę to w późniejszych przykładach.

```{R, fig.height=4, fig.width=4, echo = FALSE,message = FALSE, warnings = FALSE, fig.align='center'}
autoplot(box_results) +
  ggtitle('Czas generowania wykresów \n Scatter Plot') +
  theme(plot.title = element_text(hjust = 0.5))
```

### 2.3 Scatter plot
Zbadam zależność lioniową ceny od ilości recenzji.

```{R, fig.align='center'}
# graphics
  graphics::plot(price ~ sort(number_of_reviews), 
                  data = ny_data,
                  main = 'Cena mieszkania na Airbnb w zależności od ilości recenzji',
                  xlab = 'Ilość recenzji',
                  ylab = 'Cena [$]')

# ggplot2
ggplot(data = ny_data, aes(x=sort(number_of_reviews), y=price)) + 
  geom_point() +
  theme_minimal() +  
  theme(legend.title = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  ggtitle('Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku') +
  labs(y='Cena [$]', x = 'Ilość recenzji')

# lattice
lattice::xyplot(price ~ number_of_reviews, 
                  data = ny_data,
                  main = 'Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Ilość recenzji',
                  ylab = 'Cena [$]')
```


```{R, fig.show = 'hide',echo = FALSE, include = FALSE}
scatter_results <- microbenchmark(
  
  graphics = graphics::plot(price ~ sort(number_of_reviews), 
                  data = ny_data,
                  main = 'Cena mieszkania na Airbnb w zależności od ilości recenzji',
                  xlab = 'Ilość recenzji',
                  ylab = 'Cena [$]')
,

# ggplot2
ggplot2 = ggplot(data = ny_data, aes(x=sort(number_of_reviews), y=price)) + 
  geom_point() +
  theme_minimal() +  
  theme(legend.title = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  ggtitle('Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku') +
  labs(y='Cena [$]', x = 'Ilość recenzji')
,

# lattice
lattice = lattice::xyplot(price ~ number_of_reviews, 
                  data = ny_data,
                  main = 'Cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Ilość recenzji',
                  ylab = 'Cena [$]')
)
```

Wykres wiolinowy poniżej prezentuje 100 różnych czasów generowania dla każdej biblioteki. Tym razem również okazało się, że najszybszy w generowaniu wykresów punktowych jest *ggplot.* 

```{R, fig.height=4, fig.width=4, echo = FALSE,message = FALSE, warnings = FALSE, fig.align='center'}
autoplot(scatter_results) +
  ggtitle('Czas generowania wykresów \n Box Plot') +
  theme(plot.title = element_text(hjust = 0.5))
```

### 2.4 Histogram
Zobaczmy jak wygląda rozkład minimalnej liczby nocy jakie trzeba zarezerwować.
```{R, fig.align='center'}
# graphics
ny_data2 <- ny_data %>% 
  filter(minimum_nights < 50)

ny_hist <- hist(pull(ny_data2['minimum_nights']), nclass = 30, plot = FALSE)
graphics::plot(ny_hist,
               main = 'Histogram minimalnej liczby nocy potrzebnych do rezerwacji',
               xlab = 'Ilość dni')

# ggplot2
ggplot(ny_data2, aes(x=minimum_nights)) + 
  geom_histogram(color="black", fill="white") +
  theme_minimal() +  
  labs(y='Frequency', x = 'Ilość dni') +
  ggtitle('Histogram minimalnej liczby nocy potrzebnych do rezerwacji')

# lattice
lattice::histogram( ~ minimum_nights, 
                  data = ny_data2,
                  bins = 30,
                  main = 'Średnia cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Średnia cena [$]')

```


```{R, fig.show = 'hide',echo = FALSE, include = FALSE}
hist_results <- microbenchmark(
  
  graphics = graphics::plot(ny_hist,
               main = 'Histogram minimalnej liczby nocy potrzebnych do rezerwacji',
               xlab = 'Ilość dni')
,

# ggplot2
ggplot2 = ggplot(ny_data2, aes(x=minimum_nights)) + 
  geom_histogram(color="black", fill="white") +
  theme_minimal() +  
  labs(y='Frequency', x = 'Ilość dni') +
  ggtitle('Histogram minimalnej liczby nocy potrzebnych do rezerwacji')
,

# lattice
lattice = lattice::histogram( ~ minimum_nights, 
                  data = ny_data2,
                  bins = 30,
                  main = 'Średnia cena mieszkania na Airbnb za dobę\n w różnych dzielnicach Nowego Jorku',
                  xlab = 'Dzielnica',
                  ylab = 'Średnia cena [$]')
)
```

Wykres wiolinowy poniżej prezentuje 100 różnych czasów generowania dla każdej biblioteki. Znów okazuje się, że ggplot i lattice są najszybsze.

```{R, fig.height=4, fig.width=4, echo = FALSE,message = FALSE, warnings = FALSE, fig.align='center'}
autoplot(hist_results) +
  ggtitle('Czas generowania wykresów \n Histogramów') +
  theme(plot.title = element_text(hjust = 0.5))
```

### 2.5 Bar plot 2
Na koniec sprawdzę jeszcze jak wygląda czas generowania bar plotów z domyślnymi ustawieniami. Dodam jedynie opis osi i tytuł w każdym wypadku.
```{R, fig.align='center'}
room_agg <- ny_data %>% 
  group_by(room_type) %>% 
  summarize(cnt = n())

# graphics
  graphics::barplot(cnt ~ sort(room_type), 
                  data = room_agg,
                  main = 'Ilość rodzajów mieszkań',
                  xlab = 'Rodzaj mieszkania',
                  ylab = 'Ilość')

# ggplot2
ggplot(data = room_agg, aes(x=sort(room_type), y=cnt)) + 
  geom_bar(stat = 'identity', aes(fill = cnt)) +
  ggtitle('Ilość rodzajów mieszkań') +
  labs(y='Ilość', x = 'Rodzaj mieszkania')

# lattice
lattice::barchart(cnt ~ sort(room_type), 
                  data = room_agg,
                  main = 'Ilość rodzajów mieszkań',
                  xlab = 'Rodzaj mieszkania',
                  ylab = 'Ilość')
```

```{R, fig.show = 'hide',echo = FALSE, include = FALSE}
bar2_results <- microbenchmark(
  
  graphics = graphics::barplot(cnt ~ sort(room_type), 
                  data = room_agg,
                  main = 'Ilość rodzajów mieszkań',
                  xlab = 'Rodzaj mieszkania',
                  ylab = 'Ilość')
,

# ggplot2
ggplot2 = ggplot(data = room_agg, aes(x=sort(room_type), y=cnt)) + 
  geom_bar(stat = 'identity', aes(fill = cnt)) +
  ggtitle('Ilość rodzajów mieszkań') +
  labs(y='Ilość', x = 'Rodzaj mieszkania')
,

# lattice
lattice = lattice::barchart(cnt ~ sort(room_type), 
                  data = room_agg,
                  main = 'Ilość rodzajów mieszkań',
                  xlab = 'Rodzaj mieszkania',
                  ylab = 'Ilość')
)
```

Wykres wiolinowy poniżej prezentuje 100 różnych czasów generowania dla każdej biblioteki. Możemy zauważyć, że najszybszą biblioteką przy domyślnych parametrach pozostaje *lattice*..

```{R, fig.height=4, fig.width=4, echo = FALSE,message = FALSE, warnings = FALSE, fig.align='center'}
autoplot(bar2_results) +
  ggtitle('Czas generowania wykresów \n Bar Plot z domyślnymi ustawieniami') +
  theme(plot.title = element_text(hjust = 0.5))
```

## 3. Podsumowanie
Bazując na wynikach wszystkich symulacji jestem w stanie stwierdzić że najszybszym pakietem do generowania wykresów jest *lattice*, następnie *ggplot2* i na samym końncu, mocno odstający od pozostałych, pakiet *graphics*.
