---
title: "Praca domowa 1"
author: "Jacek Myna"
date: "2 kwietnia 2019"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(lattice)
library(tidyverse)
library(graphics)
library(microbenchmark)
library(ggplot2)

set.seed(1)
vot <- rnorm(100, 15, 5)
vot <- sort(vot, decreasing = FALSE)
phon <- "t"

df1 <- data.frame(phon, vot)

vot <- rnorm(100, -60, 15)
vot <- sort(vot, decreasing = FALSE)
phon <- "d"
df2 <- data.frame(phon, vot)

my_df <- rbind(df1, df2)

mbm_a <- microbenchmark("lattice" = { 
                        for(i in 1:100){
                          a1 <- bwplot(vot ~ phon, data = my_df)
                        }
                      },
                      "ggplot2" = {
                        for(i in 1:100){
                          a2 <- ggplot(my_df, aes(x = phon, y = vot)) + 
                            geom_boxplot()
                        }
                      },
                      "graphics" = {
                        for(i in 1:100){
                          a3 <- boxplot(vot ~ phon, data = my_df)
                        }
                      })
```
## lattice
```{r, warning=FALSE, message=FALSE}
a1
```
## ggplot2
```{r, warning=FALSE, message=FALSE}
a2
```
## graphics
```{r, warning=FALSE, message=FALSE}
a3
```
## podsumowanie
```{r, warning=FALSE, message=FALSE}
autoplot(mbm_a)

Temperature <- airquality$Temp

mbm_b <- microbenchmark("lattice" = { 
  for(i in 1:100){
    b1 <- histogram(~ Temperature, type = "count", nint = 30)
  }
},
"ggplot2" = {
  for(i in 1:100){
    b2 <- ggplot(airquality, aes(Temperature)) + 
      geom_histogram()
  }
},
"graphics" = {
  for(i in 1:100){
    b3 <- hist(Temperature, breaks = 30)
  }
})
```
## lattice
```{r, warning=FALSE, message=FALSE}
b1
```
## ggplot2
```{r, warning=FALSE, message=FALSE}
b2
```
## graphics
```{r, warning=FALSE, message=FALSE}
b3
```
## podsumowanie
```{r, warning=FALSE, message=FALSE}
autoplot(mbm_b)

mbm_c <- microbenchmark("lattice" = { 
  for(i in 1:100){
    c1 <- barchart(GNP ~ Year, data = longley, stack = FALSE, horizontal = FALSE, col = c("grey"))
  }
},
"ggplot2" = {
  for(i in 1:100){
    c2 <- ggplot(data = longley, aes(x=Year, y=GNP)) + 
      geom_col()
  }
},
"graphics" = {
  for(i in 1:100){
    c3 <- barplot(GNP ~ Year, data = longley)
  }
})
```
## lattice
```{r, warning=FALSE, message=FALSE}
c1
```
## ggplot2
```{r, warning=FALSE, message=FALSE}
c2
```
## graphics
```{r, warning=FALSE, message=FALSE}
c3
```
## podsumowanie
```{r, warning=FALSE, message=FALSE}
autoplot(mbm_c)

attach(mtcars)

mbm_d <- microbenchmark("lattice" = { 
  for(i in 1:100){
    d1 <- xyplot(mpg~wt, mtcars)
  }
},
"ggplot2" = {
  for(i in 1:100){
    d2 <- ggplot(mtcars, aes(x=wt, y=mpg)) +
      geom_point()
  }
},
"graphics" = {
  for(i in 1:100){
    d3 <- plot.default(mpg~wt)
  }
})
```
## lattice
```{r, warning=FALSE, message=FALSE}
d1
```
## ggplot2
```{r, warning=FALSE, message=FALSE}
d2
```
## graphics
```{r, warning=FALSE, message=FALSE}
d3
```
## podsumowanie
```{r, warning=FALSE, message=FALSE}
autoplot(mbm_d)

mbm_e <- microbenchmark("lattice" = { 
  for(i in 1:100){
    e1 <- xyplot(mpg~wt, mtcars, type = "l")
  }
},
"ggplot2" = {
  for(i in 1:100){
    e2 <- ggplot(data = mtcars, aes(x = wt, y = mpg)) +
      geom_line()
  }
},
"graphics" = {
  for(i in 1:100){
    e3 <- plot(mtcars$wt, mtcars$mpg, type = "l")
  }
})
```
## lattice
```{r, warning=FALSE, message=FALSE}
e1
```
## ggplot2
```{r, warning=FALSE, message=FALSE}
e2
```
## graphics
```{r, warning=FALSE, message=FALSE}
e3
```
## podsumowanie
```{r, warning=FALSE, message=FALSE}
autoplot(mbm_e)
```