---
title: "wyjsc"
author: "Piotr Janus"
date: "12/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(mlr)
library(drake)

```

## My wyjsciówka solution


```{r, echo=FALSE, warning=FALSE, message=FALSE}
my_wyjsciowka_plan <- drake_plan(
  load_data = read.csv("https://raw.githubusercontent.com/mini-pw/2020Z-ProgramowanieWR/master/Wyjsciowki/W2/gr1/SawickiJan/ShinyIris/iris.csv"),
  dat = load_data %>% mutate(variety = ifelse(variety == "Setosa", 'sentosa','niesentosa')),
  task = makeClassifTask(id = "wyjsc", data = dat, target = "variety"),
  bench = benchmark(learners = list(makeLearner("classif.ksvm"),
                                    makeLearner("classif.randomForest"),
                                    makeLearner("classif.nnet")), tasks = task),
  preds = data.frame(getBMRPredictions(bench)),
  plots = plotBMRBoxplots(bench),
  save_input = write.csv(dat, file = "super_data.csv")
)

make(my_wyjsciowka_plan)

```

```{r}
readd(plots)

```

```{r}
vis_drake_graph(drake_config(my_wyjsciowka_plan))
```
